<?php
/**
 * @category  Bunited
 * @package   Bunited\SimpleOptions
 * @author    Berin Kozlic - beringgmu@gmail.com
 * @copyright 2018 Berin Kozlic
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block \Magento\ConfigurableProduct\Block\Product\View\Type\Configurable*/

$_product    = $block->getProduct();
$_attributes = $block->decorateArray($block->getAllowAttributes());
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <?php foreach ($_attributes as $_attribute): ?>
        <div class="field configurable required">
            <label class="label" for="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId(); ?>">
                <span><?= $block->escapeHtml($_attribute->getProductAttribute()->getStoreLabel()); ?></span>
            </label>
            <div class="control">
                <select name="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId(); ?>]"
                        data-selector="super_attribute[<?= /* @escapeNotVerified */ $_attribute->getAttributeId(); ?>]"
                        data-validate="{required:true}"
                        id="attribute<?= /* @escapeNotVerified */ $_attribute->getAttributeId(); ?>"
                        class="super-attribute-select">
                    <option value=""><?= /* @escapeNotVerified */ __('Choose an Option...'); ?></option>
                </select>
            </div>
        </div>
    <?php endforeach; ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "simpleOptionsConfigurable": {
                    "spConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig(); ?>,
                    "gallerySwitchStrategy": "<?= /* @escapeNotVerified */ $block->getGallerySwitchStrategy(); ?>",
                    "jsonSimpleConfig": <?= /* @escapeNotVerified */ $block->getJsonSimpleConfig(); ?>,
                    "jsonModuleConfig": <?= /* @escapeNotVerified */ $block->getJsonModuleConfig(); ?>
                }
            }
        }
    </script>
<?php endif;?>
